<?php
/**
 * Created by PhpStorm.
 * Author: 火柴
 * Email:49650007@qq.com
 * Date: 2017/3/28
 * Time: 16:25
 */

namespace backend\widgets;


use yii\base\Widget;

class NavWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function run()
    {
        $data = [];
        return $this->render("nav", $data);
    }
}